### ISSUE TITLE
Indentation off

### ISSUE THREAD

**Issue by dereuromark** [spryker-sdk/sdk-contracts#23]
It seems some files have invalid intendation
e.g. https://github.com/spryker-sdk/sdk-contracts/blob/master/composer.json

4 spaces required

**Comment by pavelmaksimov25** [comment]
Thank you. In progress and will be fixed in the 0.4.0 release shortly.

**Comment by dereuromark** [comment]
You missed this, but you can just fix in in master, thats fine. doesnt need a release.

**Comment by pavelmaksimov25** [comment]
You already did. Thanks.

**Comment by dereuromark** [comment]
No, I did not - https://github.com/spryker-sdk/sdk-contracts/blob/master/composer.json

**Comment by pavelmaksimov25** [comment]
Sorry. Done.
